### ISSUE TITLE
Issues - Discussion

### ISSUE THREAD

**Issue by syedmehtabali** [saurabh-m-w/PasswordManager#3]
**Issues I have seen in the App**

- Creating a new account takes too much time & same for login 
- Password eye toggle icon is not working 

I am open to discuss to improve this app

**Comment by saurabh-m-w** [comment]
As I paused database monogo db app , that why it was not working,I have now resumed mongo db app,so now app its working fine.And you will able to create and login into account.
For password toggle ,on click functionlity is not implemented.

**Comment by syedmehtabali** [comment]
Okay, I got it can you please merge my PR? I have removed the deprecated widgets from the app and we can work further on this
